version: '3.8'
services:
  eureka-server:
    image: ismindirov/eureka-server
    ports:
      - "8761:8761"
    networks:
      - eureka-net

  eureka-client:
    image: ismindirov/eureka-client
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
      - SPRING_APPLICATION_NAME=eureka-client
    depends_on:
      - eureka-server
    networks:
      - eureka-net

networks:
  eureka-net:
    driver: bridge
