global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'eureka-server'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['eureka-server:8761']

  - job_name: 'eureka-client'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['eureka-client:8080']
